[package]
name = "magic_box"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc="0.2.121"
log="0.4.16"
wayland-sys = { version="0.29.4", features=["server", "client", "egl", "cursor"] }